question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "The first computer bug was formed by faulty wires.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "MacOS is based on Linux.", "correct_answer": "False",
                          "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "AMD created the first consumer 64-bit processor.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "The first dual-core CPU was the Intel Pentium D.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.","correct_answer":"False","incorrect_answers":["True"]}
]